package hive

// RANDOM_CHARSET_NUMERIC 随机字符，包含所有数字
const RANDOM_CHARSET_NUMERIC = "0123456789"

// RANDOM_CHARSET_ALPHA_UPPER 随机字符，仅含大写字母
const RANDOM_CHARSET_ALPHA_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

// RANDOM_CHARSET_ALPHA_LOWER 随机字符，仅含小写字母
const RANDOM_CHARSET_ALPHA_LOWER = "abcdefghijklmnopqrstuvwxyz"

// RANDOM_CHARSET_ALPHA_NUMERIC 随机字符，所有所有字母和数字
const RANDOM_CHARSET_ALPHA_NUMERIC = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
